use bls12_381::{G1Affine, G1Projective, Scalar};
use std::fmt::{self};

use crate::{
    bls_id_from_u32, to_g1_affine, BLSPubkeyRaw, BLSSecretRaw, ByteConvertible, HexConvertible,
};

use crate::crypto::traits::*;

#[derive(Clone, Copy, PartialEq)]
pub struct BlsG1 {
    pub g1: G1Affine,
}

#[derive(Clone, Copy, PartialEq)]
pub struct BlsScalar {
    pub scalar: Scalar,
}

impl ByteConvertible for BlsG1 {
    type Error = Box<dyn std::error::Error>;
    type RawBytes = BLSPubkeyRaw;

    fn from_bytes(bytes: &Self::RawBytes) -> Result<Self, Self::Error>
    where
        Self: Sized,
    {
        Ok(BlsG1 {
            g1: to_g1_affine(bytes),
        })
    }
    fn from_bytes_safe(bytes: &Self::RawBytes) -> Result<Self, Self::Error>
    where
        Self: Sized,
    {
        Self::from_bytes(bytes)
    }
    fn to_bytes(&self) -> Self::RawBytes {
        Self::RawBytes::from(self.g1.to_compressed())
    }
}

impl TScalar for BlsScalar {
    fn mul(self, other: &Self) -> Self {
        BlsScalar {
            scalar: self.scalar * other.scalar,
        }
    }

    fn sub(self, other: &Self) -> Self {
        BlsScalar {
            scalar: self.scalar - other.scalar,
        }
    }

    fn is_zero(self) -> bool {
        self.scalar == Scalar::zero()
    }

    fn invert(self) -> Self {
        Self {
            scalar: self.scalar.invert().expect("invalid scalar"),
        }
    }

    fn from_u32(x: u32) -> Self {
        BlsScalar {
            scalar: bls_id_from_u32(x),
        }
    }
}

impl ByteConvertible for BlsScalar {
    type Error = Box<dyn std::error::Error>;
    type RawBytes = BLSSecretRaw;

    fn from_bytes(bytes: &Self::RawBytes) -> Result<Self, Self::Error>
    where
        Self: Sized,
    {
        let mut le_bytes: Self::RawBytes = *bytes;
        le_bytes.reverse();
        Ok(BlsScalar {
            scalar: Scalar::from_bytes(&le_bytes).expect("invalid scalar"),
        })
    }
    fn from_bytes_safe(bytes: &Self::RawBytes) -> Result<Self, Self::Error>
    where
        Self: Sized,
    {
        Self::from_bytes(bytes)
    }
    fn to_bytes(&self) -> Self::RawBytes {
        let mut be_bytes = self.scalar.to_bytes();
        be_bytes.reverse();
        Self::RawBytes::from(be_bytes)
    }
}

impl fmt::Display for BlsScalar {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "{}", self.to_bytes().to_hex())
    }
}

impl TPoint for BlsG1 {
    type Scalar = BlsScalar;
    fn identity() -> Self {
        BlsG1 {
            g1: G1Affine::identity(),
        }
    }

    fn add(self, other: &Self) -> Self {
        let gp1 = G1Projective::from(self.g1);
        let ogp1 = G1Projective::from(other.g1);
        Self {
            g1: G1Affine::from(gp1 + ogp1),
        }
    }

    fn mul_scalar(self, other: &Self::Scalar) -> Self {
        let gp1 = G1Projective::from(self.g1);
        Self {
            g1: G1Affine::from(gp1 * other.scalar),
        }
    }
}

impl fmt::Display for BlsG1 {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "{}", self.to_hex())
    }
}

#[derive(Clone)]
pub struct BlsG1Curve {}

impl Curve for BlsG1Curve {
    type Point = BlsG1;
    type Scalar = BlsScalar;
}

// https://en.wikipedia.org/wiki/Shamir%27s_Secret_Sharing
//
// In Shamir's secret sharing, a secret is encoded as a n-degree polynomial
// F where the secret value is equal to F(0). Here, F(0) is provided as mask[0].
//
// A key share is generated by evaluating the polynomial in the `id` point.
// Later we can use at least N of these points to recover the original secret.
//
// Furthermore, if we sign some message M with at least K of the secret key
// shares we can restore from them the signature of the same message signed
// with original secret key.
//
// For a more gentle introductiont to Shamir's secret sharing, see also:
//
// https://github.com/dashpay/dips/blob/master/dip-0006/bls_m-of-n_threshold_scheme_and_dkg.md
// https://medium.com/toruslabs/what-distributed-key-generation-is-866adc79620
pub fn evaluate_polynomial<C: Curve>(cfs: &[C::Point], x: &C::Scalar) -> C::Point {
    let count = cfs.len();
    if count == 0 {
        C::Point::identity()
    } else if count == 1 {
        cfs[0]
    } else {
        let mut y = cfs[count - 1];
        for i in 2..(count + 1) {
            y = y.mul_scalar(x);
            y = y.add(&cfs[count - i]);
        }
        y
    }
}

#[allow(clippy::assign_op_pattern)]
#[allow(clippy::needless_range_loop)]
pub fn lagrange_interpolation<C: Curve>(
    y_vec: &[C::Point],
    x_vec: &[C::Scalar],
) -> Result<C::Point, Box<dyn std::error::Error>> {
    let k = x_vec.len();
    if k == 0 || k != y_vec.len() {
        return Err(Box::new(std::io::Error::new(
            std::io::ErrorKind::InvalidData,
            "invalid inputs",
        )));
    }
    if k == 1 {
        return Ok(y_vec[0]);
    }

    // We calculate L(0) so we can simplify
    // (X - X0) .. (X - Xj-1) * (X - Xj+1) .. (X - Xk) to just X0 * X1 .. Xk
    // Later we can divide by Xi for each basis polynomial li(0)
    let mut a = x_vec[0];
    for i in 1..k {
        //a *= x_vec[i];
        a.mul_assign(&x_vec[i]);
    }
    if a.is_zero() {
        return Err(Box::new(std::io::Error::new(
            std::io::ErrorKind::InvalidData,
            "zero secret share id",
        )));
    }
    // Pre-allocate vectors for batch processing
    let mut terms = Vec::with_capacity(k);
    let mut denominators = Vec::with_capacity(k);

    for i in 0..k {
        let mut b = x_vec[i];
        for j in 0..k {
            if j != i {
                let v = x_vec[j].sub(&x_vec[i]);
                if v.is_zero() {
                    return Err(Box::new(std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "duplicate secret share id",
                    )));
                }
                b.mul_assign(&v);
            }
        }
        denominators.push(b);
    }

    let inv_denominators = batch_invert::<C>(&denominators);

    for i in 0..k {
        let li0 = a.mul(&inv_denominators[i]);
        terms.push(y_vec[i].mul_scalar(&li0));
    }

    // Batch add all terms
    Ok(batch_add_points::<C>(&terms))
}

#[allow(clippy::assign_op_pattern)]
pub fn agg_coefficients<C: Curve>(verification_vectors: &[Vec<C::Point>]) -> Vec<C::Point> {
    if verification_vectors.is_empty() {
        return Vec::new();
    }
    let num_vectors = verification_vectors.len();
    let vector_len = verification_vectors[0].len();

    // Pre-allocate the result vector
    let mut final_cfs = Vec::with_capacity(vector_len);

    // Batch point additions for better cache locality and performance
    for i in 0..vector_len {
        // Collect all points at position i for batch addition
        let mut points_to_sum = Vec::with_capacity(num_vectors);
        for v in verification_vectors {
            points_to_sum.push(v[i]);
        }

        // Perform batched addition
        let sum = batch_add_points::<C>(&points_to_sum);
        final_cfs.push(sum);
    }
    final_cfs
}

// Optimized batch point addition function for elliptic curve operations
pub fn batch_add_points<C: Curve>(points: &[C::Point]) -> C::Point {
    if points.is_empty() {
        return C::Point::identity();
    }

    if points.len() == 1 {
        return points[0];
    }

    // For small numbers of points, use sequential addition
    if points.len() <= 4 {
        let mut sum = points[0];
        for point in &points[1..] {
            sum = sum.add(point);
        }
        return sum;
    }

    // For larger numbers, use a binary tree approach to reduce depth
    let mut current_points = points.to_vec();

    while current_points.len() > 1 {
        let mut next_level = Vec::new();
        let mut i = 0;
        while i < current_points.len() {
            if i + 1 < current_points.len() {
                // Add pairs
                next_level.push(current_points[i].add(&current_points[i + 1]));
                i += 2;
            } else {
                // Handle odd element
                next_level.push(current_points[i]);
                i += 1;
            }
        }
        current_points = next_level;
    }

    current_points[0]
}

fn batch_invert<C: Curve>(scalars: &[C::Scalar]) -> Vec<C::Scalar> {
    if scalars.is_empty() {
        return Vec::new();
    }

    let mut products = Vec::with_capacity(scalars.len());
    let mut current_product = C::Scalar::from_u32(1);

    for s in scalars {
        current_product = current_product.mul(s);
        products.push(current_product);
    }

    let mut inv = products[products.len() - 1].invert();
    let mut result = vec![C::Scalar::from_u32(0); scalars.len()];

    for i in (1..scalars.len()).rev() {
        result[i] = inv.mul(&products[i - 1]);
        inv = inv.mul(&scalars[i]);
    }
    result[0] = inv;
    result
}

#[cfg(test)]
mod tests {
    use crate::crypto::*;
    use crate::types::*;
    use bls12_381::*;

    // Helper functions to reduce test code duplication

    fn hex_to_bls_g1(hex_str: &str) -> BlsG1 {
        let pk_raw: BLSPubkeyRaw = hex::decode(hex_str).unwrap().try_into().unwrap();
        BlsG1 {
            g1: G1Affine::from_compressed(&pk_raw).into_option().unwrap(),
        }
    }

    fn hexes_to_bls_g1s(hex_strings: &[&str]) -> Vec<BlsG1> {
        hex_strings.iter().map(|hex| hex_to_bls_g1(hex)).collect()
    }

    fn hex_to_g1_affine(hex_str: &str) -> G1Affine {
        let pk_raw: BLSPubkeyRaw = hex::decode(hex_str).unwrap().try_into().unwrap();
        G1Affine::from_compressed(&pk_raw).into_option().unwrap()
    }

    fn hex_to_g2_affine(hex_str: &str) -> G2Affine {
        let sig_raw: BLSSignatureRaw = hex::decode(hex_str).unwrap().try_into().unwrap();
        G2Affine::from_compressed(&sig_raw).into_option().unwrap()
    }

    use super::*;

    #[test]
    fn test_batch_invert_basic() {
        let scalars = vec![
            BlsScalar::from_u32(2),
            BlsScalar::from_u32(3),
            BlsScalar::from_u32(4),
            BlsScalar::from_u32(5),
        ];

        let inverted = batch_invert::<BlsG1Curve>(&scalars);

        assert_eq!(scalars.len(), inverted.len());

        for i in 0..scalars.len() {
            let product = scalars[i].mul(&inverted[i]);
            assert_eq!(product.scalar, Scalar::one());
        }
    }

    #[test]
    fn test_batch_invert_empty() {
        let scalars: Vec<BlsScalar> = vec![];
        let inverted = batch_invert::<BlsG1Curve>(&scalars);
        assert!(inverted.is_empty());
    }

    #[test]
    fn test_batch_invert_single() {
        let scalar = BlsScalar::from_u32(42);
        let scalars = vec![scalar];

        let inverted = batch_invert::<BlsG1Curve>(&scalars);

        assert_eq!(inverted.len(), 1);
        assert_eq!(inverted[0].scalar, scalar.invert().scalar);
    }

    #[test]
    fn test_verify_signature() {
        let data = hex::decode("2f901d5cec8722e44afd59e94d0a56bf1506a72a0a60709920aad714d1a2ece0")
            .unwrap();
        let pk = hex_to_g1_affine("90346f9c5f3c09d96ea02acd0220daa8459f03866ed938c798e3716e42c7e033c9a7ef66a10f83af06d5c00b508c6d0f");
        let sig = hex_to_g2_affine("a9c08eff13742f78f1e5929888f223b5b5b12b4836b5417c5a135cf24f4e2a4c66a6cdef91be3098b7e7a6a63903b61302e3cf2b8653101da245cf01a8d82b25debe7b18a3a2eb1778f8628fd2c59c8687f6e048a31250fbc2804c20043b8443");
        assert!(bls_verify(&pk, &sig, &data));

        let invalida_data = hex::decode("00").unwrap();
        assert!(!bls_verify(&pk, &sig, &invalida_data));

        let wrong_pk = hex_to_g1_affine("98876a81fe982573ec5f986956bf9bf0bcb5349d95c3c8da0aefd05a49fea6215f59b0696f906547baed90ab245804e8");
        assert!(!bls_verify(&wrong_pk, &sig, &data));

        let bad_sig = hex_to_g2_affine("999e7b24bee2587d687e8f358ed10627ef57ec54935bd7a500bbbb18a57e7aa21b800f8b1f487a980d7c93918fdbd8020b66ce9a9e5788a4826e610ac937d8c2ce0ad9c0ee9a5732cf73052493e9a500cc5100a15bdbf9e5b79104db52dbf07c");
        assert!(!bls_verify(&pk, &bad_sig, &data))
    }

    #[test]
    fn test_evaluate_polynomial() {
        let pks = hexes_to_bls_g1s(&[
            "92cad77a95432bc1030d81b5465cb69be672c1dd0da752230bf8112f8449b03149e7fa208a6fae460a9f0a1d5bd175e9",
            "98876a81fe982573ec5f986956bf9bf0bcb5349d95c3c8da0aefd05a49fea6215f59b0696f906547baed90ab245804e8",
            "ad2c4e5b631fbded449ede4dca2d040b9c7eae58d1e73b3050486c1ba22c15a92d9ff13c05c356f974447e4fca84864a",
        ]);

        let target = "af8e0095ecc662f65b95ce57e5bd2f8739ff93b0621a1ad53f5616538d1323ff40e6e9ddd7132298710974fe6fc0344e";

        let id = BlsScalar::from_u32(1);

        let result = evaluate_polynomial::<BlsG1Curve>(&pks, &id).g1;

        assert!(hex::encode(result.to_compressed()) == target);
    }

    #[test]
    fn test_evaluate_polynomial_bad_base_keys() {
        let pks = hexes_to_bls_g1s(&[
            "92cad77a95432bc1030d81b5465cb69be672c1dd0da752230bf8112f8449b03149e7fa208a6fae460a9f0a1d5bd175e9",
            "92cad77a95432bc1030d81b5465cb69be672c1dd0da752230bf8112f8449b03149e7fa208a6fae460a9f0a1d5bd175e9",
            "92cad77a95432bc1030d81b5465cb69be672c1dd0da752230bf8112f8449b03149e7fa208a6fae460a9f0a1d5bd175e9",
        ]);

        let target = "af8e0095ecc662f65b95ce57e5bd2f8739ff93b0621a1ad53f5616538d1323ff40e6e9ddd7132298710974fe6fc0344e";

        let id = BlsScalar::from_u32(1);

        let result = evaluate_polynomial::<BlsG1Curve>(&pks, &id).g1;

        assert!(hex::encode(result.to_compressed()) != target);
    }

    #[test]
    fn test_lagrange_interpolation() {
        let pks = hexes_to_bls_g1s(&[
            "8da434e68daef9af33e39ab727557a3cd86d7991cd6b545746bf92c8edec37012912cfa2292a21512bce9040a1c0e502",
            "a3cd061aab6013f7561978959482d79e9ca636392bc94d4bcad9cb6f90fe2cdf52100f211052f1570db0ca690b6a9903",
            "8cbfb6cb7af927cfe5fb17621df7036de539b7ff4aa0620cdc218d6b7fe7f2e714a96bdeddb2a0dc24867a90594427e1",
            "9892b390d9d3000c7bf04763006fbc617b7ba9c261fff35094aec3f43599f2c254ae667d9ba135747309b77cd02f1fbc",
            "b255c8a66fd1a13373537e8a4ba258f4990c141fc3c06daccda0711f5ebaffc092f0e5b0e4454e6344e2f97957be4017",
        ]);

        let target = "a31d9a483703cd0da9873e5e76b4de5f7035d0a73d79b3be8667daa4fc7065a1bbb5bf77787fcf2a35bd327eecc4fa6b";

        let ids = vec![
            BlsScalar::from_u32(1),
            BlsScalar::from_u32(2),
            BlsScalar::from_u32(3),
            BlsScalar::from_u32(4),
            BlsScalar::from_u32(5),
        ];

        let result = lagrange_interpolation::<BlsG1Curve>(&pks, &ids).unwrap().g1;

        assert!(hex::encode(result.to_compressed()) == target);
    }

    #[test]
    fn test_lagrange_interpolation_out_of_order() {
        let pks = hexes_to_bls_g1s(&[
            "b255c8a66fd1a13373537e8a4ba258f4990c141fc3c06daccda0711f5ebaffc092f0e5b0e4454e6344e2f97957be4017",
            "8da434e68daef9af33e39ab727557a3cd86d7991cd6b545746bf92c8edec37012912cfa2292a21512bce9040a1c0e502",
            "a3cd061aab6013f7561978959482d79e9ca636392bc94d4bcad9cb6f90fe2cdf52100f211052f1570db0ca690b6a9903",
            "8cbfb6cb7af927cfe5fb17621df7036de539b7ff4aa0620cdc218d6b7fe7f2e714a96bdeddb2a0dc24867a90594427e1",
            "9892b390d9d3000c7bf04763006fbc617b7ba9c261fff35094aec3f43599f2c254ae667d9ba135747309b77cd02f1fbc",
        ]);

        let target = "a31d9a483703cd0da9873e5e76b4de5f7035d0a73d79b3be8667daa4fc7065a1bbb5bf77787fcf2a35bd327eecc4fa6b";

        let ids = vec![
            BlsScalar::from_u32(5),
            BlsScalar::from_u32(1),
            BlsScalar::from_u32(2),
            BlsScalar::from_u32(3),
            BlsScalar::from_u32(4),
        ];

        let result = lagrange_interpolation::<BlsG1Curve>(&pks, &ids).unwrap().g1;

        assert!(hex::encode(result.to_compressed()) == target);
    }

    #[test]
    fn test_lagrange_interpolation_wrong_order() {
        let pks = hexes_to_bls_g1s(&[
            "a3cd061aab6013f7561978959482d79e9ca636392bc94d4bcad9cb6f90fe2cdf52100f211052f1570db0ca690b6a9903",
            "8da434e68daef9af33e39ab727557a3cd86d7991cd6b545746bf92c8edec37012912cfa2292a21512bce9040a1c0e502",
            "8cbfb6cb7af927cfe5fb17621df7036de539b7ff4aa0620cdc218d6b7fe7f2e714a96bdeddb2a0dc24867a90594427e1",
            "9892b390d9d3000c7bf04763006fbc617b7ba9c261fff35094aec3f43599f2c254ae667d9ba135747309b77cd02f1fbc",
            "b255c8a66fd1a13373537e8a4ba258f4990c141fc3c06daccda0711f5ebaffc092f0e5b0e4454e6344e2f97957be4017",
        ]);

        let target = "a31d9a483703cd0da9873e5e76b4de5f7035d0a73d79b3be8667daa4fc7065a1bbb5bf77787fcf2a35bd327eecc4fa6b";

        let ids = vec![
            BlsScalar::from_u32(1),
            BlsScalar::from_u32(2),
            BlsScalar::from_u32(3),
            BlsScalar::from_u32(4),
            BlsScalar::from_u32(5),
        ];

        let result = lagrange_interpolation::<BlsG1Curve>(&pks, &ids).unwrap().g1;

        assert!(hex::encode(result.to_compressed()) != target);
    }

    #[test]
    fn test_lagrange_interpolation_wrong_base_keys() {
        let pks = hexes_to_bls_g1s(&[
            "a3cd061aab6013f7561978959482d79e9ca636392bc94d4bcad9cb6f90fe2cdf52100f211052f1570db0ca690b6a9903",
            "a3cd061aab6013f7561978959482d79e9ca636392bc94d4bcad9cb6f90fe2cdf52100f211052f1570db0ca690b6a9903",
            "a3cd061aab6013f7561978959482d79e9ca636392bc94d4bcad9cb6f90fe2cdf52100f211052f1570db0ca690b6a9903",
            "a3cd061aab6013f7561978959482d79e9ca636392bc94d4bcad9cb6f90fe2cdf52100f211052f1570db0ca690b6a9903",
            "a3cd061aab6013f7561978959482d79e9ca636392bc94d4bcad9cb6f90fe2cdf52100f211052f1570db0ca690b6a9903",
        ]);

        let target = "a31d9a483703cd0da9873e5e76b4de5f7035d0a73d79b3be8667daa4fc7065a1bbb5bf77787fcf2a35bd327eecc4fa6b";

        let ids = vec![
            BlsScalar::from_u32(1),
            BlsScalar::from_u32(2),
            BlsScalar::from_u32(3),
            BlsScalar::from_u32(4),
            BlsScalar::from_u32(5),
        ];

        let result = lagrange_interpolation::<BlsG1Curve>(&pks, &ids).unwrap().g1;

        assert!(hex::encode(result.to_compressed()) != target);
    }
}
