[package]
name = "dvt_abi_host"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hex = "0.4.3"
sp1-sdk = "3.4.0"
dvt_abi = { path = "../dvt_abi" }  