name: Rust CI

on:
  push:
    branches:
      - main
    paths:
      - "crates/**"
      - "Cargo.toml"
      - ".github/workflows/**"
  pull_request:
    branches:
      - main
    paths:
      - "crates/**"
      - "Cargo.toml"
      - ".github/workflows/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Check out repository
        uses: actions/checkout@v3

      # Install Rust
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      # Install SP1
      - name: Install SP1 toolchain
        run: |
          curl -L https://sp1.succinct.xyz | bash
          PATH="$PATH:~/.sp1/bin"
          sp1up

      # Run Tests
      - name: Run Tests
        run: make test

      # Run Formatting Check
      - name: Check Code Formatting
        run: cargo fmt -- --check
