name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install SP1 toolchain
      run: |
        curl -L https://sp1.succinct.xyz | bash
        PATH="$PATH:~/.sp1/bin"
        sp1up

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: make test
